# Fix player names function based on Transfermarkt online sources
fix_player_names <- function(player_name_vector) {
    map_chr(
        player_name_vector,
        ~ case_when(
            str_detect(., "Ali Al Hamadi") ~ "Ali Al-Hamadi",
            str_detect(., "Darwin Nunez") ~ "Darwin Núñez",
            str_detect(., "Luis Diaz") ~ "Luis Díaz",
            str_detect(., "Andy Robertson") ~ "Andrew Robertson",
            str_detect(., "Ibrahima Konate") ~ "Ibrahima Konaté",
            str_detect(., "Ibrahim Sangare") ~ "Ibrahim Sangaré",
            str_detect(., "Illia Zabarnyi") ~ "Ilya Zabarnyi",
            str_detect(., "Issa Kabore") ~ "Issa Kaboré",
            str_detect(., "Julian Araujo") ~ "Julián Araujo",
            str_detect(., "Kostas Tsimikas") ~ "Konstantinos Tsimikas",
            str_detect(., "Martin Odegaard") ~ "Martin Ødegaard",
            str_detect(., "Fabio Vieira") ~ "Fábio Vieira",
            str_detect(., "Fabio Carvalho") ~ "Fábio Carvalho",
            str_detect(., "Gabriel Magalhaes") ~ "Gabriel Magalhães",
            str_detect(., "Jorgen Strand Larsen") ~ "Jørgen Strand Larsen",
            str_detect(., "Hee-Chan Hwang|Hwang Hee-Chan") ~ "Hee-chan Hwang",
            str_detect(., "Ui-Jo Hwang|Hwang Ui-Jo") ~ "Ui-jo Hwang",
            str_detect(., "Goncalo Guedes") ~ "Gonçalo Guedes",
            str_detect(., "Joao Gomes") ~ "João Gomes",
            str_detect(., "Rayan Ait-Nouri") ~ "Rayan Aït-Nouri",
            str_detect(., "Toti Gomes") ~ "Toti",
            str_detect(., "Abdoulaye Doucoure") ~ "Abdoulaye Doucouré",
            str_detect(., "Jesper Lindstrom") ~ "Jesper Lindstrøm",
            str_detect(., "Jake OBrien") ~ "Jake O'Brien",
            str_detect(., "Vitalii Mykolenko") ~ "Vitaliy Mykolenko",
            str_detect(., "Joao Pedro") ~ "João Pedro",
            str_detect(., "Valentin Barco") ~ "Valentín Barco",
            str_detect(., "Igor Julio") ~ "Igor",
            str_detect(., "Joel Veltman") ~ "Joël Veltman",
            str_detect(., "Odeluga Offiah") ~ "Odel Offiah",
            str_detect(., "Miguel Almiron") ~ "Miguel Almirón",
            str_detect(., "Bruno Guimaraes") ~ "Bruno Guimarães",
            str_detect(., "Fabian Schar") ~ "Fabian Schär",
            str_detect(., "Sekou Mara") ~ "Sékou Mara",
            str_detect(., "Ben Brereton") ~ "Ben Brereton Díaz",
            str_detect(., "Sam Amo-Ameyaw") ~ "Samuel Amo-Ameyaw",
            str_detect(., "Tyler Dibling") ~ "Tyler Dibling",
            str_detect(., "Niclas Fullkrug") ~ "Niclas Füllkrug",
            str_detect(., "Lucas Paqueta") ~ "Lucas Paquetá",
            str_detect(., "Guido Rodriguez") ~ "Guido Rodríguez",
            str_detect(., "Emerson Palmieri") ~ "Emerson",
            str_detect(., "Maximilian Kilman") ~ "Max Kilman",
            str_detect(., "Vladimir Coufal") ~ "Vladimír Coufal",
            str_detect(., "Emiliano Buendia") ~ "Emiliano Buendía",
            str_detect(., "Alex Moreno") ~ "Álex Moreno",
            str_detect(., "Yehor Yarmoliuk") ~ "Yegor Yarmolyuk",
            str_detect(., "Christian Norgaard") ~ "Christian Nørgaard",
            str_detect(., "Ji-Soo Kim|Kim Ji-Soo") ~ "Ji-soo Kim",
            str_detect(., "Mark OMahony") ~ "Mark O'Mahony",
            str_detect(., "Maximo Perrone") ~ "Máximo Perrone",
            str_detect(., "Nicolas Dominguez") ~ "Nicolás Domínguez",
            str_detect(., "Seamus Coleman") ~ "Séamus Coleman",
            str_detect(., "Mathias Jorgensen") ~ "Mathias Jørgensen",
            str_detect(., "Ismaila Sarr") ~ "Ismaïla Sarr",
            str_detect(., "Cheick Doucoure") ~ "Cheick Doucouré",
            str_detect(., "Daniel Munoz") ~ "Daniel Muñoz",
            str_detect(., "Marc Guehi") ~ "Marc Guéhi",
            str_detect(., "Mykhailo Mudryk") ~ "Mykhaylo Mudryk",
            str_detect(., "Enzo Fernandez") ~ "Enzo Fernández",
            str_detect(., "Romeo Lavia") ~ "Roméo Lavia",
            str_detect(., "Benoit Badiashile") ~ "Benoît Badiashile",
            str_detect(., "Moises Caicedo") ~ "Moisés Caicedo",
            str_detect(., "Jeremy Doku") ~ "Jérémy Doku",
            str_detect(., "Nico OReilly") ~ "Nico O'Reilly",
            str_detect(., "Nathan Ake") ~ "Nathan Aké",
            str_detect(., "Ruben Dias") ~ "Rúben Dias",
            str_detect(., "Thomas Cannon") ~ "Tom Cannon",
            str_detect(., "Abdul Fatawu") ~ "Issahaku Fatawu",
            str_detect(., "Wanya Marcal") ~ "Wanya Marçal",
            str_detect(., "Boubakary Soumare") ~ "Boubakary Soumaré",
            str_detect(., "Ben Nelson") ~ "Ben Nelson",
            str_detect(., "Heung-Min Son|Son Heung-Min") ~ "Heung-min Son",
            str_detect(., "Pape Sarr") ~ "Pape Matar Sarr",
            str_detect(., "Radu Dragusin") ~ "Radu Drăgușin",
            str_detect(., "Willy-Arnaud Boly") ~ "Willy Boly",
            str_detect(., "Boubacar Traore") ~ "Boubacar Traoré",
            str_detect(., "Edson Alvarez") ~ "Edson Álvarez",
            TRUE ~ . # Default case to return the original player name
        )
    )
}